# Generated by Django 5.2.3 on 2025-07-02 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productmanager', '0002_alter_product_price_gross_alter_product_price_net'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forceInStock', models.BooleanField(default=False)),
                ('currentStock', models.FloatField(default=0.0)),
                ('lowestStock', models.FloatField(default=0.0)),
                ('highestStock', models.FloatField(default=0.0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productmanager.product')),
            ],
        ),
    ]
