# Generated by Django 5.0.6 on 2024-07-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
