# Generated by Django 5.0.6 on 2024-07-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_gross',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_net',
            field=models.FloatField(),
        ),
    ]
