# Generated by Django 5.0.6 on 2024-07-10 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productmanager', '0001_initial'),
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('net', models.FloatField()),
                ('gross', models.FloatField()),
                ('steueranteil', models.FloatField()),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('net', models.FloatField()),
                ('gross', models.FloatField()),
                ('total_net', models.FloatField()),
                ('total_gross', models.FloatField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cart.cart')),
                ('product_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entry', to='productmanager.product')),
            ],
        ),
    ]
