# Generated by Django 5.0.6 on 2024-07-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='steueranteil',
            new_name='tax_value',
        ),
        migrations.AddField(
            model_name='entry',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
