# Generated by Django 5.0.6 on 2024-07-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_steueranteil_cart_tax_value_entry_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='gross',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='net',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tax_value',
            field=models.FloatField(default=0, null=True),
        ),
    ]
