# Generated by Django 5.0.6 on 2024-07-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_cart_id_alter_cart_gross_alter_cart_net_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='product_view',
        ),
    ]
